title: Hello, I'm Alex Xue
logo: 
description: I'm a second year CS major and CO minor, check out my socials below!
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
linkedin_url: https://www.linkedin.com/in/alexxue/
github_url: https://github.com/Xue-Alex
devpost_url: https://devpost.com/alexxue2001
